services:
  new-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: new-api:source-local
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /opt/new-api/data:/data
      - /opt/new-api/logs:/app/logs
    env_file:
      - .env.runtime
